Add support for ext ctrls
raymanfx/libv4l-rs pull request #40
Opened 2021-07-18 15:15 UTC by cazou

This adds a basic Extended controls support. The v4l2 API provides a way to write arrays of data that are here passed as Vec<T>.

2021-07-19 09:25 UTC, raymanfx requested changes
Thanks for the PR!
There are multiple minor observations and one potentional API design issue from what I can see.

2021-07-19 09:25 UTC, raymanfx commented on src/control.rs
> -    CompoundTypes   = 0x0100,
Please do not remove the `CompoundTypes` member here.

2021-07-19 09:25 UTC, raymanfx commented on src/device.rs
> +                    control.size = val.len() as u32 * 2;
Use `std::mem::size_of` here instead of the `2` constant.

2021-07-19 09:25 UTC, raymanfx commented on src/device.rs
> +                    control.size = val.len() as u32 * 4;
Same here: use `std::mem::size_of` instead.

2021-07-19 09:25 UTC, raymanfx commented on src/device.rs
> +    fn set_base_control(&self, id: u32, val: i32) -> io::Result<()> {
This function should take a `val: Control` value instead of a `i32` here so we can easily add support for the other base controls in the future. Just forward the original `val` variable from the `set_control` function.

2021-07-19 09:25 UTC, raymanfx commented on src/device.rs
> +    fn set_ext_control(&self, id: u32, ctrl: Control) -> io::Result<()> {
I'm not sure whether this actually reflects the v4l2 API all that well.
The docs [1] state: "These ioctls allow the caller to get or set multiple controls atomically."
.. which means we should expose an API which allows clients to pass multiple controls at once. Furthermore, the v4l2 API allows you to pass an array of `v4l2_ext_controls` structs, so could set a string control and an integer control simultaneously (unless I'm misinterpreting the docs).

Could you please check on this and lay out your understanding of the API?
It seems like the proposed types like `CompoundU8` etc. are a poor match here.

[1] https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/vidioc-g-ext-ctrls.html

2021-07-19 12:26 UTC, cazou commented on src/device.rs
> +    fn set_ext_control(&self, id: u32, ctrl: Control) -> io::Result<()> {
Well, the API allows you to pass multiple values, but it can pass a table of one multiple times. Although, I agree that it is not reflecting the API correctly.
A better way would be to change this function to use a `Vec<Control>`. The advantage is that base control can be set by the Extended controls API as well.

I wanted to not change the `v4l::control::Control` API but we might not have a choice.

2021-07-19 12:26 UTC, cazou commented on src/control.rs
> -    CompoundTypes   = 0x0100,
Well I can't have CompoundTypes and CompoundU8 at the same value in an Enum. But I can revert this as they are not being used.

2021-07-19 16:41 UTC, raymanfx commented on src/control.rs
> -    CompoundTypes   = 0x0100,
True, sorry about that. I'm fine with the current change.

2021-07-19 16:44 UTC, raymanfx commented on src/device.rs
> +    fn set_ext_control(&self, id: u32, ctrl: Control) -> io::Result<()> {
The `table of one multiple times` approach falls apart whenever controls need to be changed in lockstep aka atomically.

I'm fine with changing the API here. Keeping the current function and exposing a new one which takes a Vec/slice will probably weird out users who are not all that familiar with the v4l2 API.

2021-07-22 19:17 UTC, cazou commented
@raymanfx I see that the checks failed. Apparently, the videodev2.h header might be different on the distribution used on Travis (Ubuntu Xenial, kerne 4.4) and mine (Arch Linux, kernel 5.12.15)
This is the v4l2_ext_controls structure on my computer:
```
struct v4l2_ext_controls {
        union {
                __u32 ctrl_class;
                __u32 which;
        };
        __u32 count;
        __u32 error_idx;
        __s32 request_fd;
        __u32 reserved[1];
        struct v4l2_ext_control *controls;
};
```

But there is no `which` in Ubuntu Xenial:
```
struct v4l2_ext_controls {
	__u32 ctrl_class;
	__u32 count;
	__u32 error_idx;
	__u32 reserved[2];
	struct v4l2_ext_control *controls;
};
```
It works transparently for C apps but bindgen adds a `__bindgen_anon_1` for unions. Do you know how to work with that ? Should the CI be updated to a newer version ? Xenial is not supported anymore

2021-07-22 21:16 UTC, raymanfx commented
This is a tricky one..
I'm going to ask the bindgen authors about this, since this is the first time I encounter such an issue. Worst case, I can bump the CI machine to Bionic (18.04 LTS) - although I would really prefer to keep the support for older Linux versions.

bindgen issue: https://github.com/rust-lang/rust-bindgen/issues/2077

2021-07-23 10:54 UTC, raymanfx reviewed
The `next` branch contains some changes to the control code that this change will conflict with. I will probably merge `next` into `master` today. You should be able to rebase this PR rather easily though, the semantics did not change much.

2021-07-23 10:54 UTC, raymanfx commented on src/control.rs
> +pub enum ControlValue {
Rename this to just `Value` - the module already has `control` in it and `control::ControlValue` looks awkward imo.

2021-07-23 10:57 UTC, raymanfx commented
Regarding the `v4l2_ext_controls` struct - I think we'll have to bite the bullet and carry our own copy of the struct. We should probably create a new module `videodev` in the v4l2 path here: https://github.com/raymanfx/libv4l-rs/tree/master/src/v4l2 and move the struct there.

2021-07-25 15:47 UTC, raymanfx commented
Let me know whether you are happy with the changes I made. The least *bad* way I found to deal with the bindgen issue is to carry our own struct for now. There should not really be a possibility for issues creeping up there since the C struct layout is enforced.

2021-07-25 16:38 UTC, cazou commented
Looks good to me ! I was actually slowly doing that (I started learning Rust like 2 weeks ago in my free time so I'm not all familiar with everything yet).
Only thing I would have done differently  is naming the field `ctrl_class` for this context because `which` is used when getting the default value of an extended control. But it doesn't really change anything.

2021-07-25 17:46 UTC, cazou commented
I just repushed the commits with my email address, not the work one

2021-07-25 17:59 UTC, cazou commented
And didn't keep your commit, sorry, can you push it again from your local branch ?

2021-07-25 18:48 UTC, raymanfx commented
> Only thing I would have done differently is naming the field `ctrl_class` for this context because `which` is used when getting the default value of an extended control. But it doesn't really change anything.

The docs [1] for the `which` field state that the `ctrl_class` field can be used for backwards compatibility purposes, but it's deprecated? Unless I'm reading those wrong.

[1] https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/vidioc-g-ext-ctrls.html#c.v4l2_ext_controls

> And didn't keep your commit, sorry, can you push it again from your local branch ?

Sure.

2021-07-25 18:54 UTC, merged