Avoid extra ioctl by allowing control query by description
raymanfx/libv4l-rs pull request #62
Opened 2022-09-15 20:07 UTC by donkeyteethUX

Changes based on discussion on #60, specifically comments from @MarijnS95.

- Add `get_control` which takes a `&Description` and requires only 1 ioctl.
- Deprecate `control` getter in favor of more explicit `get_control_from_id` (and document preference for `get_control`).
- Bump minor version.

2022-09-15 20:43 UTC, MarijnS95 requested changes

2022-09-15 20:43 UTC, MarijnS95 commented on Cargo.toml
> +version = "0.14.0"
Leave this up to the maintainer.

2022-09-15 20:43 UTC, MarijnS95 commented on src/device.rs
> +    pub fn get_control(&self, desc: &Description) -> io::Result<Control> {
No get_ prefix please: https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter

2022-09-15 20:43 UTC, MarijnS95 commented on src/device.rs
> +    /// Requires an extra syscall compared to `get_control`.
Intradoc link?

2022-09-15 20:43 UTC, MarijnS95 commented on src/device.rs
> +        unsafe {
I personally prefer to keep the scopes of unsafe blocks as small as possible, even if it requires a few more.

2022-09-15 20:43 UTC, MarijnS95 commented on src/device.rs
> +    pub fn control(&self, id: u32) -> io::Result<Control> {
Bumping from 0.13 to 0.14 allows making breaking changes, so I don't think it's necessary to go through a deprecation "protocol" if we document this in the changelog.

2022-09-15 20:43 UTC, MarijnS95 commented on src/device.rs
> +    /// Returns the current control value from its description
Intradoc link for `` [`Description`] ``?

2022-09-16 12:17 UTC, raymanfx commented
I am not entirely convinced increasing the API surface is worth it just to avoid a single ioctl. This might very well be a case of premature optimization. Are you running into some actual issues that motivate this change?

2022-09-16 12:59 UTC, MarijnS95 commented
> I am not entirely convinced increasing the API surface is worth it just to avoid a single ioctl. This might very well be a case of premature optimization. Are you running into some actual issues that motivate this change?

I only suggested this to be able to pass an `&Description` instead of an untyped `u32` which seemed a bit more clear to me. It's not premature optimization as much as it is removing unnecessary code that shouldn't have run/been there in the first place, IMO.

2022-09-16 19:16 UTC, donkeyteethUX commented
@raymanfx agreed that it's not a huge difference. Still, my app calls `control()` for each available control inside an egui render loop. This might seem excessive, but it's simpler and safer to keep the driver as the single source of truth rather than caching anything. `strace` shows around 1000 ioctl / second before, and 600 after, and the code is slightly more explicit as @MarijnS95 points out.

2022-09-19 03:50 UTC, donkeyteethUX commented on Cargo.toml
> +version = "0.14.0"
Accepting it is certainly up to the maintainer. The PR now makes a breaking change, so I think it makes sense to promptly bump the version.

2022-09-19 19:55 UTC, MarijnS95 commented on Cargo.toml
> +version = "0.14.0"
I prefer to mention the **breaking** changes in the PR description instead, allowing the maintainer to plan ahead when to merge it or aim to (merge and) release non-breaking changes as a patch-release first. In addition certain release helper tools automatically bump the version, which _could_ cause `0.14` to be accidentally skipped.

2022-09-23 17:44 UTC, raymanfx requested changes

2023-01-22 04:24 UTC, donkeyteethUX commented
Bump, after addressing old comment & rebasing this.

2023-01-22 22:27 UTC, MarijnS95 requested changes

2023-01-22 22:27 UTC, MarijnS95 commented on src/device.rs
> +    /// Convenience method to get the current control for an ID.
s/for an/by?

2023-01-22 22:27 UTC, MarijnS95 commented on src/device.rs
> +    /// Requires an extra syscall compared to [`control`].
The only reason the rustdoc build step doesn't fail is because this links to the `src/control.rs` module. Prefix it with `Device::` or `Self::` to get the right scoped symbol, and suffix with `()` to:

1. Make the reader aware that this link is pointing to _a function_;
2. Make rustdoc aware (and fail if not) that this points to a function.

```suggestion
    /// Requires an extra syscall compared to [`Device::control()`].
```

2023-01-22 22:27 UTC, MarijnS95 commented on src/device.rs
> +                    control::Value::Integer(v4l2_ctrl.__bindgen_anon_1.value64 as i64)
Why is this undoing #66 _and_ introducing a clippy lint error?

2023-02-03 13:55 UTC, MarijnS95 commented
@donkeyteethUX reverse bump: this is close to ready if you address the minor but remaining isuses.

2023-02-03 18:36 UTC, donkeyteethUX commented
> @donkeyteethUX reverse bump: this is close to ready if you address the minor but remaining isuses.

Thanks -- will-do when I get a chance. I'm swamped at work but haven't forgotten about it.

2023-02-07 16:17 UTC, raymanfx commented
Looks good to me. Any objections?

2023-02-07 21:17 UTC, MarijnS95 reviewed
I'm not fond of conflating PRs with unrelated new-Rust-version clippy fixes as it takes away from the main semantic change, but will leave it to @raymanfx to decide to split that out to a separate PR (i.e. do we use rebase merges?).

2023-02-07 21:17 UTC, MarijnS95 commented on src/device.rs
> +    /// Requires an extra syscall compared to [Device::control()].
Don't forget the backticks that were present in the original PR _and_ my review suggestion.

2023-03-01 14:06 UTC, MarijnS95 commented
Ping again, we still have two comments open and shouldn't conflate this PR with unrelated clippy changes.

2023-11-01 10:24 UTC, MarijnS95 approved these changes

2023-11-05 18:45 UTC, raymanfx commented on src/device.rs
> +    pub fn control_from_id(&self, id: u32) -> io::Result<Control> {
IMO, this can be removed. We don't need backwards compatibility here, no need to inflate the API surface when the new function does the same thing, but better.

2023-11-05 23:17 UTC, MarijnS95 commented on src/device.rs
> +    pub fn control_from_id(&self, id: u32) -> io::Result<Control> {
Agreed if we're pushing to land this in a breaking release.

2023-11-09 12:04 UTC, raymanfx approved these changes
Looks good to me. I still think the API is a touch too close to the raw C v4l2 API, but we can do iterative improvements. It's something I need to think about and sketch out separately.

2023-11-09 13:01 UTC, MarijnS95 commented
@raymanfx do you mean the API added by this PR specifically, or the control API in general? If anything it seems this function is now more high-level by taking something typed instead of a generic `i32`.

2023-11-10 15:58 UTC, merged